services:
    Ram34\CodePostalBundle\FieldType\CodePostal\Type:
        tags:
            - {name: ezpublish.fieldType, alias: codepostal}
            - {name: ezpublish.fieldType.nameable, alias: codepostal}

    Ram34\CodePostalBundle\FieldType\CodePostal\LegacyConverter:
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: codepostal}

    Ram34\CodePostalBundle\FieldType\CodePostal\FormMapper:
        autowire: true
        tags:
            - {name: ez.fieldFormMapper.value, fieldType: codepostal}