services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Netgen\InformationCollectionBundle\:
        autowire: true
        resource: '../../*'
        exclude: '../../{Entity,Repository}'

    Netgen\InformationCollectionBundle\Limitation\AnonymizeCollectionLimitationType:
        autowire: true
        arguments:
            - "@ezpublish.api.persistence_handler"
        tags:
            - { name: ezpublish.limitationType, alias: AnonymizeCollection }