services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Netgen\InformationCollectionBundle\:
        autowire: true
        resource: '../../*'
        exclude: '../../{Entity,Repository}'

    Netgen\InformationCollectionBundle\Limitation\AnonymizeCollectionLimitationType:
        autowire: true
        arguments:
            - "@ezpublish.api.persistence_handler"
        tags:
            - { name: ezpublish.limitationType, alias: AnonymizeCollection }

    Netgen\InformationCollectionBundle\Limitation\AnonymizeCollectionLimitationMapper:
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@?logger"
        tags:
            - { name: ez.limitation.formMapper, limitationType: AnonymizeCollection }
            - { name: ez.limitation.valueMapper, limitationType: AnonymizeCollection }