services:
#    ez_systems_extending_tutorial.example:
#        class: EzSystems\ExtendingTutorialBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    EzSystems\ExtendingTutorialBundle\Tab\Dashboard\Everyone\EveryoneArticleTab:
        autowire: true
        autoconfigure: true
        public: false
        tags:
            - { name: ezplatform.tab, group: dashboard-everyone }