services:
    Ram34\CityFieldTypeBundle\FieldType\City\Type:
        autowire: true
        tags:
            - {name: ezpublish.fieldType, alias: ramcity}

    Ram34\CityFieldTypeBundle\FieldType\City\LegacyConverter:
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ramcity}