services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ram34\CityFieldTypeBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository}'