services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\TweetFieldTypeBundle\:
        resource: '../../src/EzSystems/TweetFieldTypeBundle/*'
        exclude: '../../src/EzSystems/TweetFieldTypeBundle/{Entity,Repository}'

    EzSystems\TweetFieldTypeBundle\Controller:
        resource: '../../src/EzSystems/TweetFieldTypeBundle/Controller'
        tags: ['controller.service_arguments']